import type {PackageJson} from './package_json.js';

export const package_json = {
	name: '@grogarden/gro',
	description: 'task runner and toolkit extending SvelteKit',
	version: '0.96.4',
	bin: {gro: 'dist/gro.js'},
	license: 'MIT',
	homepage: 'https://www.grogarden.org/',
	author: {name: 'Ryan Atkinson', email: 'mail@ryanatkn.com', url: 'https://www.ryanatkn.com/'},
	repository: {type: 'git', url: 'git+https://github.com/grogarden/gro.git'},
	bugs: {url: 'https://github.com/grogarden/gro/issues', email: 'mail@ryanatkn.com'},
	type: 'module',
	engines: {node: '>=20.7'},
	scripts: {
		build: 'rm -rf .gro dist && svelte-package && chmod +x ./dist/gro.js && npm link -f',
		start: 'gro dev',
		test: 'gro test',
	},
	keywords: [
		'web',
		'tools',
		'task runner',
		'tasks',
		'codegen',
		'svelte',
		'sveltekit',
		'vite',
		'typescript',
	],
	files: ['dist'],
	dependencies: {
		'@grogarden/util': '^0.15.2',
		'@ryanatkn/json-schema-to-typescript': '^11.1.5',
		chokidar: '^3.5.3',
		dotenv: '^16.3.1',
		'es-module-lexer': '^1.3.1',
		kleur: '^4.1.5',
		mri: '^1.2.0',
		prettier: '^3.0.3',
		'prettier-plugin-svelte': '^3.0.3',
		'tiny-glob': '^0.2.9',
		'ts-morph': '^20.0.0',
		tslib: '^2.6.2',
		zod: '^3.22.4',
	},
	peerDependencies: {esbuild: '^0.18', svelte: '*'},
	devDependencies: {
		'@changesets/changelog-git': '^0.1.14',
		'@changesets/types': '^5.2.1',
		'@feltjs/eslint-config': '^0.4.1',
		'@fuz.dev/fuz': '^0.75.2',
		'@fuz.dev/fuz_library': '^0.14.2',
		'@sveltejs/adapter-static': '^2.0.3',
		'@sveltejs/kit': '^1.27.1',
		'@sveltejs/package': '^2.2.2',
		'@types/fs-extra': '^11.0.3',
		'@types/node': '^20.8.9',
		'@typescript-eslint/eslint-plugin': '^6.9.0',
		'@typescript-eslint/parser': '^6.9.0',
		esbuild: '^0.18.0',
		eslint: '^8.52.0',
		'eslint-plugin-svelte': '^2.34.0',
		svelte: '^4.2.2',
		'svelte-check': '^3.5.2',
		typescript: '^5.2.2',
		uvu: '^0.5.6',
	},
	eslintConfig: {root: true, extends: '@feltjs', rules: {'no-console': 1}},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	exports: {
		'.': {default: './dist/index.js', types: './dist/index.d.ts'},
		'./args.js': {default: './dist/args.js', types: './dist/args.d.ts'},
		'./build.task.js': {default: './dist/build.task.js', types: './dist/build.task.d.ts'},
		'./changeset.task.js': {
			default: './dist/changeset.task.js',
			types: './dist/changeset.task.d.ts',
		},
		'./check.task.js': {default: './dist/check.task.js', types: './dist/check.task.d.ts'},
		'./clean_fs.js': {default: './dist/clean_fs.js', types: './dist/clean_fs.d.ts'},
		'./clean.task.js': {default: './dist/clean.task.js', types: './dist/clean.task.d.ts'},
		'./cli.js': {default: './dist/cli.js', types: './dist/cli.d.ts'},
		'./commit.task.js': {default: './dist/commit.task.js', types: './dist/commit.task.d.ts'},
		'./config.js': {default: './dist/config.js', types: './dist/config.d.ts'},
		'./deploy.task.js': {default: './dist/deploy.task.js', types: './dist/deploy.task.d.ts'},
		'./dev.task.js': {default: './dist/dev.task.js', types: './dist/dev.task.d.ts'},
		'./env.js': {default: './dist/env.js', types: './dist/env.d.ts'},
		'./esbuild_helpers.js': {
			default: './dist/esbuild_helpers.js',
			types: './dist/esbuild_helpers.d.ts',
		},
		'./esbuild_plugin_external_worker.js': {
			default: './dist/esbuild_plugin_external_worker.js',
			types: './dist/esbuild_plugin_external_worker.d.ts',
		},
		'./esbuild_plugin_svelte.js': {
			default: './dist/esbuild_plugin_svelte.js',
			types: './dist/esbuild_plugin_svelte.d.ts',
		},
		'./esbuild_plugin_sveltekit_local_imports.js': {
			default: './dist/esbuild_plugin_sveltekit_local_imports.js',
			types: './dist/esbuild_plugin_sveltekit_local_imports.d.ts',
		},
		'./esbuild_plugin_sveltekit_shim_alias.js': {
			default: './dist/esbuild_plugin_sveltekit_shim_alias.js',
			types: './dist/esbuild_plugin_sveltekit_shim_alias.d.ts',
		},
		'./esbuild_plugin_sveltekit_shim_app.js': {
			default: './dist/esbuild_plugin_sveltekit_shim_app.js',
			types: './dist/esbuild_plugin_sveltekit_shim_app.d.ts',
		},
		'./esbuild_plugin_sveltekit_shim_env.js': {
			default: './dist/esbuild_plugin_sveltekit_shim_env.js',
			types: './dist/esbuild_plugin_sveltekit_shim_env.d.ts',
		},
		'./exists.js': {default: './dist/exists.js', types: './dist/exists.d.ts'},
		'./format_directory.js': {
			default: './dist/format_directory.js',
			types: './dist/format_directory.d.ts',
		},
		'./format_file.js': {default: './dist/format_file.js', types: './dist/format_file.d.ts'},
		'./format.task.js': {default: './dist/format.task.js', types: './dist/format.task.d.ts'},
		'./gen_module.js': {default: './dist/gen_module.js', types: './dist/gen_module.d.ts'},
		'./gen_schemas.js': {default: './dist/gen_schemas.js', types: './dist/gen_schemas.d.ts'},
		'./gen.task.js': {default: './dist/gen.task.js', types: './dist/gen.task.d.ts'},
		'./gen.js': {default: './dist/gen.js', types: './dist/gen.d.ts'},
		'./git.js': {default: './dist/git.js', types: './dist/git.d.ts'},
		'./gro_plugin_gen.js': {
			default: './dist/gro_plugin_gen.js',
			types: './dist/gro_plugin_gen.d.ts',
		},
		'./gro_plugin_library.js': {
			default: './dist/gro_plugin_library.js',
			types: './dist/gro_plugin_library.d.ts',
		},
		'./gro_plugin_server.js': {
			default: './dist/gro_plugin_server.js',
			types: './dist/gro_plugin_server.d.ts',
		},
		'./gro_plugin_sveltekit_frontend.js': {
			default: './dist/gro_plugin_sveltekit_frontend.js',
			types: './dist/gro_plugin_sveltekit_frontend.d.ts',
		},
		'./gro.config.default.js': {
			default: './dist/gro.config.default.js',
			types: './dist/gro.config.default.d.ts',
		},
		'./gro.js': {default: './dist/gro.js', types: './dist/gro.d.ts'},
		'./hash.js': {default: './dist/hash.js', types: './dist/hash.d.ts'},
		'./input_path.js': {default: './dist/input_path.js', types: './dist/input_path.d.ts'},
		'./invoke_task.js': {default: './dist/invoke_task.js', types: './dist/invoke_task.d.ts'},
		'./invoke.js': {default: './dist/invoke.js', types: './dist/invoke.d.ts'},
		'./lint.task.js': {default: './dist/lint.task.js', types: './dist/lint.task.d.ts'},
		'./loader.js': {default: './dist/loader.js', types: './dist/loader.d.ts'},
		'./module.js': {default: './dist/module.js', types: './dist/module.d.ts'},
		'./modules.js': {default: './dist/modules.js', types: './dist/modules.d.ts'},
		'./package_json.js': {default: './dist/package_json.js', types: './dist/package_json.d.ts'},
		'./package.gen.js': {default: './dist/package.gen.js', types: './dist/package.gen.d.ts'},
		'./package.js': {default: './dist/package.js', types: './dist/package.d.ts'},
		'./path.js': {default: './dist/path.js', types: './dist/path.d.ts'},
		'./paths.js': {default: './dist/paths.js', types: './dist/paths.d.ts'},
		'./plugin.js': {default: './dist/plugin.js', types: './dist/plugin.d.ts'},
		'./print_task.js': {default: './dist/print_task.js', types: './dist/print_task.d.ts'},
		'./publish.task.js': {default: './dist/publish.task.js', types: './dist/publish.task.d.ts'},
		'./release.task.js': {default: './dist/release.task.js', types: './dist/release.task.d.ts'},
		'./resolve_node_specifier.js': {
			default: './dist/resolve_node_specifier.js',
			types: './dist/resolve_node_specifier.d.ts',
		},
		'./resolve_specifier.js': {
			default: './dist/resolve_specifier.js',
			types: './dist/resolve_specifier.d.ts',
		},
		'./run_gen.js': {default: './dist/run_gen.js', types: './dist/run_gen.d.ts'},
		'./run_task.js': {default: './dist/run_task.js', types: './dist/run_task.d.ts'},
		'./schema.js': {default: './dist/schema.js', types: './dist/schema.d.ts'},
		'./search_fs.js': {default: './dist/search_fs.js', types: './dist/search_fs.d.ts'},
		'./sveltekit_config.js': {
			default: './dist/sveltekit_config.js',
			types: './dist/sveltekit_config.d.ts',
		},
		'./sveltekit_shim_app_environment.js': {
			default: './dist/sveltekit_shim_app_environment.js',
			types: './dist/sveltekit_shim_app_environment.d.ts',
		},
		'./sveltekit_shim_app_forms.js': {
			default: './dist/sveltekit_shim_app_forms.js',
			types: './dist/sveltekit_shim_app_forms.d.ts',
		},
		'./sveltekit_shim_app_navigation.js': {
			default: './dist/sveltekit_shim_app_navigation.js',
			types: './dist/sveltekit_shim_app_navigation.d.ts',
		},
		'./sveltekit_shim_app_paths.js': {
			default: './dist/sveltekit_shim_app_paths.js',
			types: './dist/sveltekit_shim_app_paths.d.ts',
		},
		'./sveltekit_shim_app_stores.js': {
			default: './dist/sveltekit_shim_app_stores.js',
			types: './dist/sveltekit_shim_app_stores.d.ts',
		},
		'./sveltekit_shim_app.js': {
			default: './dist/sveltekit_shim_app.js',
			types: './dist/sveltekit_shim_app.d.ts',
		},
		'./sveltekit_shim_env.js': {
			default: './dist/sveltekit_shim_env.js',
			types: './dist/sveltekit_shim_env.d.ts',
		},
		'./sync.task.js': {default: './dist/sync.task.js', types: './dist/sync.task.d.ts'},
		'./task_module.js': {default: './dist/task_module.js', types: './dist/task_module.d.ts'},
		'./task.js': {default: './dist/task.js', types: './dist/task.d.ts'},
		'./test.task.js': {default: './dist/test.task.js', types: './dist/test.task.d.ts'},
		'./throttle.js': {default: './dist/throttle.js', types: './dist/throttle.d.ts'},
		'./type_imports.js': {default: './dist/type_imports.js', types: './dist/type_imports.d.ts'},
		'./typecheck.task.js': {
			default: './dist/typecheck.task.js',
			types: './dist/typecheck.task.d.ts',
		},
		'./upgrade.task.js': {default: './dist/upgrade.task.js', types: './dist/upgrade.task.d.ts'},
		'./watch_dir.js': {default: './dist/watch_dir.js', types: './dist/watch_dir.d.ts'},
	},
	modules: {
		'.': {
			id: 'index.ts',
			declarations: [
				{name: 'GroConfig'},
				{name: 'CreateGroConfig'},
				{name: 'Plugin'},
				{name: 'replace_plugin'},
				{name: 'Gen'},
				{name: 'GenContext'},
				{name: 'Task'},
				{name: 'TaskContext'},
				{name: 'TaskError'},
			],
		},
		'./args.js': {
			id: 'args.ts',
			declarations: [
				{name: 'Args'},
				{name: 'ArgValue'},
				{name: 'ArgSchema'},
				{name: 'parse_args'},
				{name: 'serialize_args'},
				{name: 'to_task_args'},
				{name: 'to_raw_rest_args'},
				{name: 'to_forwarded_args'},
				{name: 'to_forwarded_args_by_command'},
				{name: 'print_command_args'},
			],
		},
		'./build.task.js': {id: 'build.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./changeset.task.js': {
			id: 'changeset.task.ts',
			declarations: [
				{name: 'Args'},
				{name: 'task'},
				{name: 'ChangesetCallback'},
				{name: 'UpdateWrittenConfig'},
				{name: 'update_changeset_config'},
				{name: 'load_changeset_config'},
				{name: 'load_changeset_config_contents'},
				{name: 'write_changeset_config'},
				{name: 'serialize_changeset_config'},
				{name: 'parse_changeset_config'},
			],
		},
		'./check.task.js': {id: 'check.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./clean_fs.js': {id: 'clean_fs.ts', declarations: [{name: 'clean_fs'}]},
		'./clean.task.js': {id: 'clean.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./cli.js': {id: 'cli.ts', declarations: [{name: 'find_cli'}, {name: 'spawn_cli'}]},
		'./commit.task.js': {id: 'commit.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./config.js': {
			id: 'config.ts',
			declarations: [
				{name: 'GroConfig'},
				{name: 'CreateGroConfig'},
				{name: 'create_empty_config'},
				{name: 'GroConfigModule'},
				{name: 'load_config'},
				{name: 'validate_config_module'},
			],
		},
		'./deploy.task.js': {id: 'deploy.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./dev.task.js': {
			id: 'dev.task.ts',
			declarations: [{name: 'Args'}, {name: 'DevTaskContext'}, {name: 'task'}],
		},
		'./env.js': {
			id: 'env.ts',
			declarations: [
				{name: 'load_env'},
				{name: 'merge_envs'},
				{name: 'is_private_env'},
				{name: 'is_public_env'},
			],
		},
		'./esbuild_helpers.js': {
			id: 'esbuild_helpers.ts',
			declarations: [
				{name: 'print_build_result'},
				{name: 'to_define_import_meta_env'},
				{name: 'ts_transform_options'},
			],
		},
		'./esbuild_plugin_external_worker.js': {
			id: 'esbuild_plugin_external_worker.ts',
			declarations: [{name: 'Options'}, {name: 'esbuild_plugin_external_worker'}],
		},
		'./esbuild_plugin_svelte.js': {
			id: 'esbuild_plugin_svelte.ts',
			declarations: [{name: 'Options'}, {name: 'esbuild_plugin_svelte'}],
		},
		'./esbuild_plugin_sveltekit_local_imports.js': {
			id: 'esbuild_plugin_sveltekit_local_imports.ts',
			declarations: [{name: 'esbuild_plugin_sveltekit_local_imports'}],
		},
		'./esbuild_plugin_sveltekit_shim_alias.js': {
			id: 'esbuild_plugin_sveltekit_shim_alias.ts',
			declarations: [{name: 'Options'}, {name: 'esbuild_plugin_sveltekit_shim_alias'}],
		},
		'./esbuild_plugin_sveltekit_shim_app.js': {
			id: 'esbuild_plugin_sveltekit_shim_app.ts',
			declarations: [{name: 'Options'}, {name: 'esbuild_plugin_sveltekit_shim_app'}],
		},
		'./esbuild_plugin_sveltekit_shim_env.js': {
			id: 'esbuild_plugin_sveltekit_shim_env.ts',
			declarations: [{name: 'Options'}, {name: 'esbuild_plugin_sveltekit_shim_env'}],
		},
		'./exists.js': {id: 'exists.ts', declarations: [{name: 'exists'}]},
		'./format_directory.js': {
			id: 'format_directory.ts',
			declarations: [{name: 'format_directory'}],
		},
		'./format_file.js': {id: 'format_file.ts', declarations: [{name: 'format_file'}]},
		'./format.task.js': {id: 'format.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./gen_module.js': {
			id: 'gen_module.ts',
			declarations: [
				{name: 'GEN_FILE_PATTERN_TEXT'},
				{name: 'GEN_FILE_PATTERN'},
				{name: 'is_gen_path'},
				{name: 'GEN_SCHEMA_FILE_PATTERN_TEXT'},
				{name: 'GEN_SCHEMA_FILE_PATTERN'},
				{name: 'GEN_SCHEMA_PATH_SUFFIX'},
				{name: 'GEN_SCHEMA_IDENTIFIER_SUFFIX'},
				{name: 'GenModuleType'},
				{name: 'GenModule'},
				{name: 'BasicGenModule'},
				{name: 'SchemaGenModule'},
				{name: 'to_gen_module_type'},
				{name: 'gen_module_meta'},
				{name: 'validate_gen_module'},
				{name: 'GenModuleMeta'},
				{name: 'BasicGenModuleMeta'},
				{name: 'SchemaGenModuleMeta'},
				{name: 'load_gen_module'},
				{name: 'CheckGenModuleResult'},
				{name: 'check_gen_modules'},
				{name: 'check_gen_module'},
				{name: 'find_gen_modules'},
			],
		},
		'./gen_schemas.js': {
			id: 'gen_schemas.ts',
			declarations: [{name: 'gen_schemas'}, {name: 'to_schemas_from_modules'}],
		},
		'./gen.task.js': {id: 'gen.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./gen.js': {
			id: 'gen.ts',
			declarations: [
				{name: 'GenResult'},
				{name: 'GenFile'},
				{name: 'Gen'},
				{name: 'GenContext'},
				{name: 'RawGenResult'},
				{name: 'RawGenFile'},
				{name: 'GenConfig'},
				{name: 'GenResults'},
				{name: 'GenModuleResult'},
				{name: 'GenModuleResultSuccess'},
				{name: 'GenModuleResultFailure'},
				{name: 'to_gen_result'},
				{name: 'to_output_file_name'},
			],
		},
		'./git.js': {
			id: 'git.ts',
			declarations: [
				{name: 'GitOrigin'},
				{name: 'GitBranch'},
				{name: 'git_current_branch_name'},
				{name: 'git_remote_branch_exists'},
				{name: 'git_local_branch_exists'},
				{name: 'git_check_clean_workspace'},
				{name: 'git_fetch'},
				{name: 'git_checkout'},
				{name: 'git_pull'},
				{name: 'git_push'},
				{name: 'git_push_to_create'},
				{name: 'git_delete_local_branch'},
				{name: 'git_delete_remote_branch'},
				{name: 'WORKTREE_DIRNAME'},
				{name: 'to_worktree_dir'},
				{name: 'git_clean_worktree'},
				{name: 'git_reset_branch_to_first_commit'},
				{name: 'git_current_commit_hash'},
				{name: 'git_current_branch_first_commit_hash'},
			],
		},
		'./gro_plugin_gen.js': {
			id: 'gro_plugin_gen.ts',
			declarations: [{name: 'TaskArgs'}, {name: 'plugin'}],
		},
		'./gro_plugin_library.js': {
			id: 'gro_plugin_library.ts',
			declarations: [{name: 'plugin'}, {name: 'has_library'}],
		},
		'./gro_plugin_server.js': {
			id: 'gro_plugin_server.ts',
			declarations: [
				{name: 'SERVER_SOURCE_ID'},
				{name: 'has_server'},
				{name: 'Options'},
				{name: 'Outpaths'},
				{name: 'CreateOutpaths'},
				{name: 'plugin'},
			],
		},
		'./gro_plugin_sveltekit_frontend.js': {
			id: 'gro_plugin_sveltekit_frontend.ts',
			declarations: [{name: 'Options'}, {name: 'HostTarget'}, {name: 'plugin'}],
		},
		'./gro.config.default.js': {
			id: 'gro.config.default.ts',
			declarations: [{name: 'default'}, {name: 'has_sveltekit_frontend'}],
		},
		'./gro.js': {id: 'gro.ts', declarations: []},
		'./hash.js': {id: 'hash.ts', declarations: [{name: 'to_hash'}]},
		'./input_path.js': {
			id: 'input_path.ts',
			declarations: [
				{name: 'resolve_input_path'},
				{name: 'resolve_input_paths'},
				{name: 'get_possible_source_ids'},
				{name: 'load_source_path_data_by_input_path'},
				{name: 'load_source_ids_by_input_path'},
			],
		},
		'./invoke_task.js': {id: 'invoke_task.ts', declarations: [{name: 'invoke_task'}]},
		'./invoke.js': {id: 'invoke.ts', declarations: []},
		'./lint.task.js': {id: 'lint.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./loader.js': {id: 'loader.ts', declarations: [{name: 'load'}, {name: 'resolve'}]},
		'./module.js': {
			id: 'module.ts',
			declarations: [
				{name: 'MODULE_PATH_SRC_PREFIX'},
				{name: 'MODULE_PATH_LIB_PREFIX'},
				{name: 'is_external_module'},
			],
		},
		'./modules.js': {
			id: 'modules.ts',
			declarations: [
				{name: 'ModuleMeta'},
				{name: 'LoadModuleResult'},
				{name: 'LoadModuleFailure'},
				{name: 'load_module'},
				{name: 'FindModulesResult'},
				{name: 'FindModulesFailure'},
				{name: 'LoadModulesResult'},
				{name: 'find_modules'},
				{name: 'load_modules'},
			],
		},
		'./package_json.js': {
			id: 'package_json.ts',
			declarations: [
				{name: 'PackageJsonRepository'},
				{name: 'PackageJsonAuthor'},
				{name: 'PackageJsonFunding'},
				{name: 'PackageJsonExports'},
				{name: 'PackageJson'},
				{name: 'MapPackageJson'},
				{name: 'EMPTY_PACKAGE_JSON'},
				{name: 'load_package_json'},
				{name: 'sync_package_json'},
				{name: 'load_gro_package_json'},
				{name: 'write_package_json'},
				{name: 'serialize_package_json'},
				{name: 'update_package_json'},
				{name: 'normalize_package_json'},
				{name: 'to_package_exports'},
			],
		},
		'./package.gen.js': {
			id: 'package.gen.ts',
			declarations: [
				{name: 'Module_Declaration'},
				{name: 'Package_Module'},
				{name: 'Package_Modules'},
				{name: 'gen'},
			],
		},
		'./package.js': {id: 'package.ts', declarations: [{name: 'package_json'}]},
		'./path.js': {
			id: 'path.ts',
			declarations: [
				{name: 'PathData'},
				{name: 'to_path_data'},
				{name: 'PathStats'},
				{name: 'PathFilter'},
			],
		},
		'./paths.js': {
			id: 'paths.ts',
			declarations: [
				{name: 'SOURCE_DIRNAME'},
				{name: 'GRO_DIRNAME'},
				{name: 'GRO_DIST_PREFIX'},
				{name: 'SERVER_DIST_PATH'},
				{name: 'LIB_DIRNAME'},
				{name: 'ROUTES_DIRNAME'},
				{name: 'GRO_DEV_DIRNAME'},
				{name: 'SOURCE_DIR'},
				{name: 'GRO_DIR'},
				{name: 'GRO_DEV_DIR'},
				{name: 'LIB_PATH'},
				{name: 'LIB_DIR'},
				{name: 'CONFIG_PATH'},
				{name: 'README_FILENAME'},
				{name: 'SVELTEKIT_CONFIG_FILENAME'},
				{name: 'VITE_CONFIG_FILENAME'},
				{name: 'SVELTEKIT_DEV_DIRNAME'},
				{name: 'SVELTEKIT_BUILD_DIRNAME'},
				{name: 'SVELTEKIT_DIST_DIRNAME'},
				{name: 'NODE_MODULES_DIRNAME'},
				{name: 'SVELTEKIT_VITE_CACHE_PATH'},
				{name: 'GITHUB_DIRNAME'},
				{name: 'GIT_DIRNAME'},
				{name: 'TSCONFIG_FILENAME'},
				{name: 'Paths'},
				{name: 'Url'},
				{name: 'Email'},
				{name: 'SourceId'},
				{name: 'BuildId'},
				{name: 'create_paths'},
				{name: 'paths_from_id'},
				{name: 'is_gro_id'},
				{name: 'to_root_path'},
				{name: 'source_id_to_base_path'},
				{name: 'base_path_to_source_id'},
				{name: 'lib_path_to_import_id'},
				{name: 'import_id_to_lib_path'},
				{name: 'to_gro_input_path'},
				{name: 'replace_root_dir'},
				{name: 'print_path'},
				{name: 'print_path_or_gro_path'},
				{name: 'replace_extension'},
				{name: 'gro_dir_basename'},
				{name: 'paths'},
				{name: 'is_this_project_gro'},
				{name: 'gro_paths'},
				{name: 'gro_sveltekit_dist_dir'},
			],
		},
		'./plugin.js': {
			id: 'plugin.ts',
			declarations: [
				{name: 'Plugin'},
				{name: 'CreateConfigPlugins'},
				{name: 'PluginContext'},
				{name: 'Plugins'},
				{name: 'replace_plugin'},
			],
		},
		'./print_task.js': {
			id: 'print_task.ts',
			declarations: [
				{name: 'log_available_tasks'},
				{name: 'log_error_reasons'},
				{name: 'print_task_help'},
			],
		},
		'./publish.task.js': {id: 'publish.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./release.task.js': {id: 'release.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./resolve_node_specifier.js': {
			id: 'resolve_node_specifier.ts',
			declarations: [
				{name: 'resolve_node_specifier'},
				{name: 'ParsedNodeSpecifier'},
				{name: 'parse_node_specifier'},
			],
		},
		'./resolve_specifier.js': {
			id: 'resolve_specifier.ts',
			declarations: [{name: 'ResolvedSpecifier'}, {name: 'resolve_specifier'}],
		},
		'./run_gen.js': {
			id: 'run_gen.ts',
			declarations: [
				{name: 'GEN_NO_PROD_MESSAGE'},
				{name: 'run_gen'},
				{name: 'to_gen_import_path'},
				{name: 'to_gen_context_imports'},
			],
		},
		'./run_task.js': {
			id: 'run_task.ts',
			declarations: [{name: 'RunTaskResult'}, {name: 'run_task'}],
		},
		'./schema.js': {
			id: 'schema.ts',
			declarations: [
				{name: 'JsonSchema'},
				{name: 'bundle_schemas'},
				{name: 'is_json_schema'},
				{name: 'to_json_schema_resolver'},
				{name: 'infer_schema_types'},
				{name: 'parse_schema_name'},
			],
		},
		'./search_fs.js': {
			id: 'search_fs.ts',
			declarations: [{name: 'SearchFsOptions'}, {name: 'search_fs'}],
		},
		'./sveltekit_config.js': {
			id: 'sveltekit_config.ts',
			declarations: [
				{name: 'load_sveltekit_config'},
				{name: 'ParsedSveltekitConfig'},
				{name: 'init_sveltekit_config'},
			],
		},
		'./sveltekit_shim_app_environment.js': {
			id: 'sveltekit_shim_app_environment.ts',
			declarations: [{name: 'browser'}, {name: 'building'}, {name: 'dev'}, {name: 'version'}],
		},
		'./sveltekit_shim_app_forms.js': {
			id: 'sveltekit_shim_app_forms.ts',
			declarations: [{name: 'applyAction'}, {name: 'deserialize'}, {name: 'enhance'}],
		},
		'./sveltekit_shim_app_navigation.js': {
			id: 'sveltekit_shim_app_navigation.ts',
			declarations: [
				{name: 'afterNavigate'},
				{name: 'beforeNavigate'},
				{name: 'disableScrollHandling'},
				{name: 'goto'},
				{name: 'invalidate'},
				{name: 'invalidateAll'},
				{name: 'preloadCode'},
				{name: 'preloadData'},
			],
		},
		'./sveltekit_shim_app_paths.js': {
			id: 'sveltekit_shim_app_paths.ts',
			declarations: [{name: 'assets'}, {name: 'base'}],
		},
		'./sveltekit_shim_app_stores.js': {
			id: 'sveltekit_shim_app_stores.ts',
			declarations: [{name: 'getStores'}, {name: 'navigating'}, {name: 'page'}, {name: 'updated'}],
		},
		'./sveltekit_shim_app.js': {
			id: 'sveltekit_shim_app.ts',
			declarations: [
				{name: 'sveltekit_shim_app_paths_matcher'},
				{name: 'sveltekit_shim_app_environment_matcher'},
				{name: 'sveltekit_shim_app_specifiers'},
				{name: 'render_sveltekit_shim_app_paths'},
				{name: 'render_sveltekit_shim_app_environment'},
			],
		},
		'./sveltekit_shim_env.js': {
			id: 'sveltekit_shim_env.ts',
			declarations: [{name: 'render_env_shim_module'}],
		},
		'./sync.task.js': {
			id: 'sync.task.ts',
			declarations: [{name: 'Args'}, {name: 'task'}, {name: 'sveltekit_sync'}],
		},
		'./task_module.js': {
			id: 'task_module.ts',
			declarations: [
				{name: 'TaskModule'},
				{name: 'TaskModuleMeta'},
				{name: 'validate_task_module'},
				{name: 'load_task_module'},
				{name: 'find_task_modules'},
				{name: 'load_task_modules'},
			],
		},
		'./task.js': {
			id: 'task.ts',
			declarations: [
				{name: 'Task'},
				{name: 'TaskContext'},
				{name: 'TASK_FILE_SUFFIX_TS'},
				{name: 'TASK_FILE_SUFFIX_JS'},
				{name: 'is_task_path'},
				{name: 'to_task_name'},
				{name: 'TaskError'},
			],
		},
		'./test.task.js': {id: 'test.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./throttle.js': {id: 'throttle.ts', declarations: [{name: 'throttle'}]},
		'./type_imports.js': {id: 'type_imports.ts', declarations: [{name: 'normalize_type_imports'}]},
		'./typecheck.task.js': {
			id: 'typecheck.task.ts',
			declarations: [{name: 'Args'}, {name: 'task'}],
		},
		'./upgrade.task.js': {id: 'upgrade.task.ts', declarations: [{name: 'Args'}, {name: 'task'}]},
		'./watch_dir.js': {
			id: 'watch_dir.ts',
			declarations: [
				{name: 'WatchNodeFs'},
				{name: 'WatcherChange'},
				{name: 'WatcherChangeType'},
				{name: 'WatcherChangeCallback'},
				{name: 'Options'},
				{name: 'watch_dir'},
			],
		},
	},
} satisfies PackageJson;
