// generated by library.gen.ts - do not edit

import type {LibraryJson} from '@fuzdev/fuz_util/library_json.js';

import json from './library.json' with {type: 'json'};

export const library_json: LibraryJson = json as LibraryJson;

// generated by library.gen.ts - do not edit
