// generated by src/build.schema.ts

export interface BuildTaskArgs {
	clean?: boolean;
	/**
	 * opt out of cleaning before building; warning! this may break your build!
	 */
	'no-clean'?: boolean;
}

// generated by src/build.schema.ts
