// generated by src/buildTask.schema.ts

export interface BuildTaskArgs {
	clean: boolean;
	/**
	 * opt out of cleaning before building; warning! this may break your build!
	 */
	'no-clean'?: boolean;
}

// generated by src/buildTask.schema.ts
