// generated by src/check.schema.ts

export interface CheckTaskArgs {
	_: string[];
	typecheck?: boolean;
	'no-typecheck'?: boolean;
	test?: boolean;
	'no-test'?: boolean;
	gen?: boolean;
	'no-gen'?: boolean;
	format?: boolean;
	'no-format'?: boolean;
	lint?: boolean;
	'no-lint'?: boolean;
}

// generated by src/check.schema.ts
