// generated by src/cleanTask.schema.ts

export interface CleanTaskArgs {
	build?: boolean;
	/**
	 * opt out of deleting the Gro build directory .gro/
	 */
	'no-build'?: boolean;
	dist?: boolean;
	/**
	 * opt out of deleting the Gro dist directory dist/
	 */
	'no-dist'?: boolean;
	/**
	 * delete the SvelteKit directory .svelte-kit/ and Vite cache
	 */
	sveltekit?: boolean;
	/**
	 * delete node_modules/
	 */
	nodemodules?: boolean;
	/**
	 * run "git remote prune" to delete local branches referencing nonexistent remote branches
	 */
	git?: boolean;
}

// generated by src/cleanTask.schema.ts
