// generated by src/deployTask.schema.ts

export interface DeployTaskArgs {
	/**
	 * output directory in dist/ - defaults to detecting 'svelte-kit' | 'browser'
	 */
	dirname?: string;
	/**
	 * source branch to build and deploy from
	 */
	source: string;
	/**
	 * target branch to deploy to
	 */
	target: string;
	/**
	 * build and prepare to deploy without actually deploying, for diagnostic and testing purposes
	 */
	dry: boolean;
	/**
	 * instead of building and deploying, just clean the git worktree and Gro cache
	 */
	clean: boolean;
	/**
	 * caution!! enable deploying and force pushing to branches like main and master
	 */
	force: boolean;
}

// generated by src/deployTask.schema.ts
