// generated by src/devTask.schema.ts

export interface DevTaskArgs {
	watch?: boolean;
	/**
	 * opt out of running a long-lived process to watch files and rebuild on changes
	 */
	'no-watch'?: boolean;
	/**
	 * ignore https credentials
	 */
	insecure?: boolean;
	/**
	 * https certificate file
	 */
	cert?: string;
	/**
	 * https certificate key file
	 */
	certkey?: string;
}

// generated by src/devTask.schema.ts
