// generated by src/formatTask.schema.ts

export interface FormatTaskArgs {
	/**
	 * exit with a nonzero code if any files are unformatted
	 */
	check: boolean;
}

// generated by src/formatTask.schema.ts
