// generated by src/genTask.schema.ts

export interface GenTaskArgs {
	/**
	 * paths to generate
	 */
	_: string[];
	/**
	 * exit with a nonzero code if any files need to be generated
	 */
	check?: boolean;
}

// generated by src/genTask.schema.ts
