// generated by src/publishTask.schema.ts

export interface PublishTaskArgs {
	/**
	 * npm version increment, like major|minor|patch
	 */
	_: string[];
	/**
	 * branch to publish from
	 */
	branch: string;
	/**
	 * build and prepare to publish without actually publishing, for diagnostic and testing purposes
	 */
	dry: boolean;
	/**
	 * if true, the package is published privately instead of the public default, using `npm publish --access restricted`
	 */
	restricted: boolean;
}

// generated by src/publishTask.schema.ts
