// generated by src/serveTask.schema.ts

export interface ServeTaskArgs {
	/**
	 * paths to serve
	 */
	_: string[];
	/**
	 * network address host
	 */
	host: string;
	/**
	 * network address port
	 */
	port: number;
	/**
	 * ignore https credentials
	 */
	insecure?: boolean;
	/**
	 * https certificate file
	 */
	cert?: string;
	/**
	 * https certificate key file
	 */
	certkey?: string;
}

// generated by src/serveTask.schema.ts
