// generated by src/upgradeTask.schema.ts

export interface UpgradeTaskArgs {
	/**
	 * names of deps to exclude from the upgrade
	 */
	_: string[];
	/**
	 * if true, print out the planned upgrades
	 */
	dry?: boolean;
}

// generated by src/upgradeTask.schema.ts
